# Generated by Django 4.2.6 on 2023-10-29 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predicted_probability', users.fields.PercentField(decimal_places=2, max_digits=5)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.form')),
                ('statement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.statement')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='statement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.statement'),
        ),
        migrations.AddField(
            model_name='form',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
