# Generated by Django 4.2.6 on 2023-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_form_rename_user_statement_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdict',
            name='Statement_verdict',
            field=models.CharField(default='', max_length=255),
        ),
    ]
