# Generated by Django 4.2.6 on 2023-11-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.statement')),
                ('verdict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.verdict')),
            ],
        ),
    ]
